```{r}

library(tidyverse)

# Defina o caminho para o diretório onde estão os arquivos txt
caminho <- "results_questao2"  # substitua pelo caminho real

# Lista os arquivos txt no diretório
arquivos <- list.files(path = caminho, pattern = "\\.txt$", full.names = TRUE)

# Lê e combina os arquivos em um único data frame
dados_questao2 <- arquivos %>%
  map_df(~ read_delim(.x, delim = " ", locale = locale(decimal_mark = ","), col_names = TRUE, trim_ws = TRUE)) |> 
  arrange(TaxaDeChegadaMedia)

# Visualiza as primeiras linhas
head(dados_questao2)



```
```{r}
ggplot(dados_questao2, aes(x = TaxaDeChegadaMedia, y = TempoMedioDeResposta)) +
       geom_point()+
        geom_line(color = "blue")+
    scale_y_continuous(limits = c(0, 1.5), breaks = (seq(0, 1.5, by = 0.25)))+
    scale_x_continuous(breaks = unique(dados_questao2$TaxaDeChegadaMedia))
```



```{r}
library(tidyverse)
# Defina o caminho para o diretório onde estão os arquivos txt
caminho <- "results_questao3"  # substitua pelo caminho real

# Lista os arquivos txt
arquivos <- list.files(path = caminho, pattern = "\\.txt$", full.names = TRUE)

# Lê e combina os arquivos em um único data frame
dados_questão3 <- arquivos |>  
  map_df(~ read_delim(.x, delim = " ", locale = locale(decimal_mark = ","), trim_ws = TRUE)) |> 
  arrange(NumServidores)

# Visualiza as primeiras linhas
dados_questão3

```
```{r}
ggplot(dados_questão3, aes(x = NumServidores, y = TempoMedioDeResposta))+
  geom_point()+
  geom_line(color = "blue")+
    scale_y_continuous(limits = c(0, 15), breaks = (seq(0, 15, by = 5)))+
  scale_x_continuous(breaks = unique(dados_questão3$NumServidores))
```

